### ISSUE TITLE
A1. Budget investment's associated image

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#1]
# Primera versión
Vamos a dividir el planteamiento en dos partes, una para los cambios que atañen al FrontEnd, y otra parte para lo referente a usuarios administradores.

**Admin**
Dado que un administrador puede crear y editar proyectos de inversión:
- ~~Un administrador debe poder añadir una imagen (opcional)~~
- ~~Un administrador debe poder añadir un texto descriptivo para la imagen para potencias el SEO
       (obligatorio si se define una imagen). Este texto se usará como "título" y como "texto alternativo"~~

**Modelo**
El modelo que nos atañe en este issue es Budget::Investment.

* [x] Añadir el campo image:string al modelo 
* [x] Añadir el campo image_description:string al modelo
* [x] Validar la extensión de la image. Inicialmente sólo permitiremos JPEG.
* [x] Validar la presencia de la descripción de la imagen sólo si se ha definido una imagen
* [x] Crear diferentes versiones (además de la original) de la imagen para optimizar la carga en cada una de las pantallas donde se renderiza la imagen. (El tamaño de las mismas está pendiente de definir, una vez validados los mockups por el core de Consul)

**Permisos**
* [x] Sólo los autores pueden realizar modificaciones en la imagen de un proyecto. 

**FrontEnd: Listado de proyectos**
  - [x] Mockup del  listado de proyectos de inversión
  - [x] Añadir una capa de un color en sustitución de la imagen si esta no existe
  - [x] Agregar una columna 2x con la imagen de proyecto
  - [x] Reducir la columna que contiene el texto de 9x a 7x
  - [x] Revisar las versiones responsive

**FrontEnd: Editar la imagen de un proyecto**
  - [x] Mockup de la página de edición de la foto de proyecto de inversión
    - Mostrar la imagen actual en una versión reducida para que el autor pueda ver la imagen actual
    - [x] Campo input[type=file] que permitirá al autor modificar la imagen.
    - [x] Campo título que permitirá al autor modificar su título.
    - [x] Añadir recomendaciones

**FrontEnd: Página de proyecto**
  - [x] Mockup de la página de proyecto de inversión
  - [x] Sólo el autor verá el botón de cambiar imagen.
  - [x] Mostrar una imagen sólo si está definida. En esta página se omite la imagen de relleno.
  - [x] Revisar las versiones responsive

# Mejoras
Este punto son ideas que aún están en el aire y que tras implementar la primera versión veremos si se implementan o no.

* [ ] Imágenes por defecto asociadas a las categorías. Estás imágenes se mostrarían en el listado de proyectos sólo cuando no se ha definido ninguna
* [x] Habilitar el acceso a las acciones de edición y actualización a los usuarios administradores

**Comment by taitus** [comment]
@voodoorai2000 We are defining first and most prioritary issue. Can you check our definition? 

Should we have to create different image versions? One for budgets index, another one for social sharing and the bigger one for budgets page.

**Comment by Senen** [comment]
Adjunto el mockup definitivo de la **página de proyecto** creado por Alberto:

**Nuevos layout abajo donde escribo**:  Subo al últimas versiones de los mockups.

**Comment by Senen** [comment]
# Mockups primera versión
Ajunto mockup para la **página de listado de proyectos** propuesto por Alberto:

**Nuevos layout abajo donde escribo**: Subo al últimas versiones de los mockups.

También habría que hacer este ajuste para alinear mejor el contenido de la derecha que varía en función del estado actual de la proyecto. Como se puede ver en la siguiente imagen **el botón de apoyo está perfectamente alineado con la descripción**.

**Nuevos layout abajo donde escribo**: Subo al últimas versiones de los mockups.

**Comment by Senen** [comment]
Hemos quitado los requerimientos de administrador ya que el proceso de creación/edición de propuestas desde el admin de momento está cerrado. Rai me ha sugerido crear una pantalla donde el autor sólo pueda editar la imagen definida. 

@agileontheweb  **Conviene definir un mockup antes de implementar este punto.**

**Comment by agileontheweb** [comment]
Subo al últimas versiones de los mockups.

**Investment list**
![investment-list](https://user-images.githubusercontent.com/1497150/27335270-37269e3a-55cc-11e7-87fb-e1b5759bb4a6.png)

**Investment show**
![investment-show](https://user-images.githubusercontent.com/1497150/27335269-3722ec9a-55cc-11e7-8f98-6f8410538494.png)

**Investment image edit**
![investment-image-edit](https://user-images.githubusercontent.com/1497150/27335268-3721f808-55cc-11e7-832b-5128fce6b651.png)
