### ISSUE TITLE
A3. Budget timeline dates

### ISSUE THREAD

**Issue by Senen** [rockandror/consul#10]
Client wants 2 dates to explain milestone better:
* [ ] start_date is required field
* [ ] end_date is optional (only for milestone ranges)

**Comment by Senen** [comment]
Esperamos la validación de Alberto, de Rai y Miguel antes de empezar la issue.

**Comment by taitus** [comment]
@Senen. Parece que esta issue para "Budgets" se va a mantener solo con el created_at.
Si al final tenemos que hacer timeline para propuestas ya abriremos otra issue.
