### ISSUE TITLE
A3. Budget investment timeline

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#2]
# A.3 Timeline
**Issue del proyecto original**: https://github.com/consul/consul/issues/1599

Sólo para los proyectos que han ganado en la fase de selección de presupuestos se añadirá una nueva pestaña llamada "Seguimiento" donde los usuarios podrán ver el estado actual del proyecto hasta que se convierta en una realidad.

## Diseño
- [x] Preparar mockup (Proporcionado por Alberto) 

## Admin
- [x] Los administradores deben poder añadir, eliminar y modificar los hitos (milestones) por las que pasa un proyecto hasta que se convierta en una realidad.
El lugar correcto donde añadir esta gestión es en Administración - Presupuestos Participativos - Ver propuestas de inversión. Cuando editamos una de las propuestas de inversión, añadiremos un CRUD básico referente a este "Seguimiento". Los campos de los que debe disponer cada "Punto de seguimiento/Checkpoint/Milestone" son: [Title, Description, Timestamps]

## FrontEnd
- [x] Los usuarios visitantes de la web podrán ver los hitos ordenados cronológicamente. (Ver mockup en los comentarios)
Se debe adaptar el show de un presupuesto participativo (ej: [example-budget-investment-show](https://decide.madrid.es/participatory_budget/investment_projects/4887)) para que después de la descripción  de la propuesta, donde aparecen los comentarios, transformarlo a un formato con pestañas con un estilo que ya existe en propuestas (ej: [example-proposal-show](https://decide.madrid.es/proposals/18839-plantacion-arboles-calle-juan-duque-y-paseo-de-los-melancolicos)). En nuestro caso, deberá  añadirse una pestaña de "Seguimiento"

**Comment by Senen** [comment]
Mockup preparado por Alberto:
![d447225c-4794-11e7-8011-36f8fc96a804](https://user-images.githubusercontent.com/15726/27286404-4ed59fee-5500-11e7-98f1-07792deaeae0.jpg)

**Comment by agileontheweb** [comment]
En este diseño se han cambiado dos cosas:
- Eliminado padding top en el title y alineado al cirulo.
- Se ha modificado el color de verde a morado.
Determinado por Alberto a través de Slack

![nuevo layout](https://user-images.githubusercontent.com/1497150/27476871-9f61fffe-580a-11e7-89f1-5673464b03de.png)

**Comment by Senen** [comment]
Done and merged in consul through Timeline 2 #1688
