### ISSUE TITLE
Manage Local Census

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#28]
### Why is this Needed?
To allow only administrator users to load the Census database through the administration panel into different ways:

1. Manually, one by one through a CRUD interface
2. Automatically through an importation process

### Description
- Create a new section under admin settings menu entry called "Manage Local Census" to manage local_census_records manually.
- Allow to import spreadsheet files and create records on database

### Current Behavior
Currently you have to load the census database manually through rails console.

### Expected Behavior
![Captura de pantalla 2019-04-03 a las 18 29 00](https://user-images.githubusercontent.com/16189/55496005-642ad300-563e-11e9-86a9-bdff4bd8ab09.png)

**Comment by Senen** [comment]
Done at consul/consul/pull/3479
