### ISSUE TITLE
B. My activity

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#4]
What
====
Show user followable activiy on user page.

How
===
Add new tab to show followed objects by user. If followable objects are owned by user, action buttons should be shown.

Screenshots
===========
![captura de pantalla 2017-07-13 a las 18 47 13](https://user-images.githubusercontent.com/15726/28177640-bf239fe0-67fb-11e7-97f8-d4a8f5f8522a.png)
![captura de pantalla 2017-07-13 a las 18 46 58](https://user-images.githubusercontent.com/15726/28177641-bf25a344-67fb-11e7-82a9-f5177877d772.png)

Test
====
Increased test coverage to:
- check followed object presence in correct accordion tab
- check "Following" tabs UI
- check action buttons presence if followable object is owned by user 

Deployment
==========
As usual.

**Comment by agileontheweb** [comment]
Añado layout comprobado por Alberto.
![siguiendo_2](https://user-images.githubusercontent.com/1497150/27548520-7878bca2-5a99-11e7-9f0e-6547632e8594.png)

Usar el `data-allow-all-closed="true"` de http://foundation.zurb.com/sites/docs/accordion.html para que puedan estar cerrados todos) habría que probarlo

**Comment by agileontheweb** [comment]
Para @taitus y @Senen 

Hice el push de la rama, pero como hemos quitado el numero ya no se encuentra en esta rama.
Se encuentra en: https://github.com/rockandror/consul/tree/my-activity

show.html : Añadido el tab con la palabra "Add translate", hay que poner el < li > en el sitio correcto cuando la funcionalidad existe ahora mismo lo puse justa antes del close del < ul > y convertir el texto en el archivo yml.

_activity_page: Añadido render following, he seguido la misma linea del mismo archivo. El nombre following no soy super seguro que es correcto con naming.

_following: Añadido each del accordion y la tabla. Cada Panel del accordion lleva un icono, 
 icon-proposal o icon-debates que tienen que cambiar según si es proposal o debate o algo más.

Estoy esperando que Alberto me conteste a una pregunta sobre el + o - que se encuentra en el accordion, porque el puse la palabra cerrar.

**Comment by taitus** [comment]
Cerramos esta issue. Se incluye dentro de #6

**Comment by taitus** [comment]
Reabrimos issue. Al final se harán dos PR independientes.

**Comment by taitus** [comment]
https://github.com/consul/consul/pull/1750
