### ISSUE TITLE
C. My recomendations

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#5]
Al entrar en decide.madrid.es si el usuario está logueado se creará un módulo en el cual aparecerán contenido (propuestas, debates, ) recomendado para el usuario en función de sus intereses.
**Aún no es seguro si la ubicación de las recomendaciones será la home o si será proposals#index, budget_investments#index y debates#index.** No obstante vamos a ir preparando los partials y el algoritmo que calcula los intereses del usuario logeado, cuando sepamos la ubicación final simplemente tendremos que adaptar el controlador para que disponga los datos necesarios para las vistas.

# Que
Mostrar recomendaciones (debates, propuestas, y proyectos de inversión) para los usuarios logeados en función de sus intereses.

Definimos interés como un string con el texto de una etiqueta.
Ejemplo de los intereses de un usuario: ["Cultura", "Salud", "Deportes"]

# Como

Calculando los intereses de un usuario a partir de las etiquetas de las propuestas o proyectos de inversión que sigue y creando unas vistas parciales para reutilizar allí donde se necesite mostrar las recomendaciones al usuario.

## Modelo

**Propuestas ciudadanas recomendadas:**
Las que dispongan de algún interés del usuario como etiqueta ordenadas por número de votos descendientemente y descartando las propuestas ya seguidas por el usuario

**Proyectos de inversión recomendados:**
Los que dispongan de algún interés del usuario como etiqueta ordenadas por número de votos descendientemente y descartando las proyectos de inversión ya seguidos por el usuario

**Debates recomendados:**
Los que dispongan de algún interés del usuario como etiqueta ordenadas por número de votos descendientemente. (Los debates aún no se pueden seguir por los usuarios)

## Vista
Con Alberto hemos decidido de crear de momento solo los partials y no ponerlo en ningún lado de porque no saben si lo quieren meter en home page o en cada sección."

Seguir este montaje.
```<%= render "recommended" %>```
Y dentro de este:
```
<%= render "recommended_debates" %>
<%= render "recommended_proposals" %>
<%= render "recommended_budgets_investments" %>
```
**Con imagen y sin imagen**

![recomendded-image](https://user-images.githubusercontent.com/1497150/28466862-17d4bcf4-6e2e-11e7-979f-9532f0083075.png)

![home-no-recommended](https://user-images.githubusercontent.com/1497150/28466863-17e3d46e-6e2e-11e7-89e8-01bee1ad8b69.png)

**Alberto comentario en Slack.**

Sobre la lista de recomendaciones, la dejaría sin imagen (por eso de que los debates no tienen, o bien poner una genérica ahí para todos los debates igual) sería más curro pero a lo mejor se podría buscar una por categoría (puedes poner una genércia y ya en Madrid la cambio yo, en consul no hace falta)

El resto perfect, eso sí, veo que has puesto unas flechas, pero si usas el “carrusel” de Foundation son círculos, puedes dejar esos estilos por defecto :slightly_smiling_face: http://foundation.zurb.com/sites/docs/orbit.html_

**Comment by agileontheweb** [comment]
Con Alberto hemos decidido de crear de momento solo los partials y no ponerlo en ningún lado de  porque no saben si lo quieren meter en home page o en cada sección."

Seguir este montaje.
<%= render "recommended" %>
Y dentro de este:
<%= render "recommended_debates" %>
<%= render "recommended_proposals" %>
<%= render "recommended_budgets_investments" %>

**Comment by agileontheweb** [comment]
La rama se encuentra en https://github.com/rockandror/consul/tree/user-recomendations

**Comment by Senen** [comment]
**Punto 1: Recomendaciones homepage**

Sobre esto envío un mockup con algunos mini cambios:

- Lo pondría más arriba, justo después del header (que imagino todo el mundo utilizará para el "proceso" más destacado).
- Aprovecharía el ancho total de cada caja, ahora se me queda un poco pequeño.
- No centraría el texto, sí los controles del slider.
- Haría más pequeños los círculos del slider.

![1_consul_home](https://user-images.githubusercontent.com/15726/28611521-573314b0-71ec-11e7-963e-c892a5484adb.jpg)

**Comment by agileontheweb** [comment]
Nuevos cambios aplicados.

![new-change](https://user-images.githubusercontent.com/1497150/28615986-4c885b38-71fb-11e7-84d4-ca1f3241dacf.png)

**Comment by taitus** [comment]
Cambios solicitados:
- [x] Eliminar de las recomendaciones los "Presupuestos Participativos"
- [x] Añadir un valor de configuración para poder activar/desactivar estas recomendaciones.
  - [x] Ejecutar Setting['feature.recommendeds'] = true o Setting['feature.recommendeds'] = false
- [x] Nuevo link en las recomendaciones para que nos redirija al index de debates/propuestas con todas las recomendaciones.
