### ISSUE TITLE
A6. Proposals/BudgetInvestments follow button

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#6]
**Propuestas y Presupuestos participativos**
* [x] Asociación polimórfica "Followable" para relacionar con un usuario
* [x] Añadir un botón "Seguir"
  * [x] Propuestas (En la página pública de la propuesta)
  * [x] Proyectos de inversión (En la página pública del proyecto)
* [x] Dar permisos a cualquier usuario logeado para seguir o dejar de seguir entidades.
  * [x] Propuestas
  * [x] Proyectos de inversión
* [x] Ocultar el botón de seguir si no hay usuario logeado
* [x] Actualizar por AJAX el botón de seguir y la pestaña de usuarios seguidores.

**Perfil de usuario**
* [x] Añadir un campo a user public_intererests:boolean

**Página de usuario**
* [x] Mostrar intereses(tags) bajo del nombre de usuario sólo cuando el usuario haya activado los permisos.

**Página de entidad**
* [x] Mostrar los usuarios que la siguen
  * [x] Hacer un mockup para determinar la mejor posición para este elemento (@alessandro)

**Notificaciones**
* [x] Mostrar las notificaciones a los usuarios que siguen una propuesta.
~~* [ ] Mostrar las notificaciones a los usuarios que siguen un presupuesto participativo???~~
  ~~* [ ] Implementar InvestmentNotificacionsController???~~

**Mi actividad** #4 
* [x] Mostrar las propuestas y presupuestos participativos que un usuario esta siguiendo en su perfil.

**Comment by Senen** [comment]
Mergeada en consul a través de https://github.com/consul/consul/pull/1727. 🥇 👏 😄
