### ISSUE TITLE
A4. Discussion Forum

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#7]
# Comunidad de Usuarios

Se pretende crear una comunidad para facilitar que los usuarios a través de una propuesta o un presupuesto participativo puedan crear diferentes "Temas" relacionados y hacer comentarios para fomentar la participación.

La comunidad de usuarios se implementará como una funcionalidad opcional para los forks, y se podrá aplicar tanto a propuestas como a proyectos de inversión.

Desglose de wireframes validados:

- [x] Enlace a la comunidad desde show de una propuesta
![1](https://user-images.githubusercontent.com/16189/28988515-6fb1df22-7970-11e7-9841-73ac7c77e279.jpg)

- [x] Página principal de la comunidad
  - [x] Selector desplegable para cambiar el orden con el que se muestran los temas
  - [x] Translate Most commented
![captura de pantalla 2017-08-09 a las 17 08 41](https://user-images.githubusercontent.com/1497150/29129004-c369a02e-7d25-11e7-8bd0-2b3d87e11e7b.png)

  - [x] Sección de "Miembros" (Se considerarán miembros a los usuarios que han participado creando temas o aportando comentarios)
  - [x] Listado de "Temas"
  - [x] Botón "Crear temas"
![2](https://user-images.githubusercontent.com/16189/28988847-31ed947c-7972-11e7-8428-b95d057c099c.jpg)

- [x] Crear un tema
![3](https://user-images.githubusercontent.com/16189/28990686-134cc9da-7980-11e7-970d-0550a439bc7f.jpg)

- [x] Pagina de un Tema (Añadir comentarios)
![6](https://user-images.githubusercontent.com/16189/28990621-6b37290c-797f-11e7-8df2-fc6189ab17f2.jpg)

**Comment by Senen** [comment]
@taitus te dejo un recordatorio: Vamos a usar el concepto "Participantes" en lugar de "Miembros"

**Comment by Senen** [comment]
Merged https://github.com/consul/consul/pull/1815. Good job @rockandror/core! 🎉 💯
