### ISSUE TITLE
A2. Geolocation map

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#8]
What
======
Allow to geolocate budget investments and proposals on the map.

Original definition was:
> Propuesta ciudadana y presupuesto participativo (prioritario en este último ?, importante en ambas)
> La propuesta se podrá geolocalizar, por el usuario administrador o creador de la propuesta, en un mapa. La opción a elegir debe ser open street maps. El mapa se mostrará al pulsar sobre la pestaña de “localización”.

How
======

We have to resolve two problems here: How administrators can configure application map default configuration at backend, and How to allow users to geolocate their proposals and budget investments at frontend.

## How administrators can configure application map 
First of all we have to create a way to allow forks to easily setup their city map. To achieve this we may create some settings records and an admin page or section to allow administrators to manage city map.

**How to store data**
To store this data and save it into settings table we should add new action "update_map" to admin/settings controller to allow administrators to configure the map by drag and drop a marker along the map.

* Administrators can enable or disable map feature from admin settings index page.
* Backend map will only be visible when feature activated.

We have to create next secrets entries on default scope:
```
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"
```

We have to create next secrets entries on production scope:
```
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"
```

We have to create next settings records:
```
# Map feature setting
Setting.create(key: 'feature.map', value: true)

# Greenwich default global position coordinates
Setting.create(key: 'map_latitude', value: 51.48)
Setting.create(key: 'map_longitude', value: 0)
Setting.create(key: 'map_zoom', value: 10)
```

We may need some js resources to use OpenStreetsMaps and to consume map tiles provider.

## How to manage the city map on frontend
* Frontend maps will be available only when map feature activated.
* Frontend maps for new proposals or budget investment should show map at default application position without marker.
* Users should be able to add or move marker to desired place by dragging it or by clicking anywhere over the map.
* Administrators and authors should be allowed to edit frontend map locations.
* Allow authors to geolocate only own proposals and budget_investments.
* Place a map marker is not mandatory. Users can delete marker by clicking link "Remove marker" and save proposal or budget investment without associated map location.
*  Proposals and budget investments without map_location defined should not show map at show page.

Screenshots
========
**Backend user interface (settings#index): Feature deactivated -> Map not rendered**
![captura de pantalla 2017-08-07 a las 12 42 31](https://user-images.githubusercontent.com/15726/29023462-06554e06-7b6e-11e7-8eec-dc2f5860fd70.png)

**Backend user interface: Feature activated -> Map rendered**
![captura de pantalla 2017-08-07 a las 12 31 02](https://user-images.githubusercontent.com/15726/29023499-358d8404-7b6e-11e7-802b-0a553b06b91a.png)

**Frontend new proposal or budget investment without marker**
![new-proposal-no-marker](https://user-images.githubusercontent.com/15726/29023694-223a2c6c-7b6f-11e7-9543-5180a7827523.jpg)

**Frontend new proposal or budget investment with marker**
![new-proposal-marker](https://user-images.githubusercontent.com/15726/29023732-3d05c830-7b6f-11e7-8188-f4e1de377524.jpg)

**Frontend show proposal or budget investment map location**
![proposal-show](https://user-images.githubusercontent.com/15726/29023761-53b81bd2-7b6f-11e7-882e-a77f9a32f991.jpg)

**Download the images on the first upload**
![proposal-show-download-images-on-first-upload](https://user-images.githubusercontent.com/16189/30383337-bdd7b51e-98a1-11e7-9138-5dfdd3b12fd9.png)

**Load images from cache**
![load-images-from-cache](https://user-images.githubusercontent.com/16189/30383446-fe53193a-98a1-11e7-9b8d-678a86eb931d.png)

Warnings
=====
See https://operations.osmfoundation.org/policies/tiles/ to investigate further.

**Comment by Senen** [comment]
@agileontheweb te adjunto los cambios que nos sugiere Alberto en las pantallas de documentos. Aplica los que son de diseño, de la parte de la barra de carga y del formulario nos ocupamos @taitus  y yo.

**Punto 1: Recomendaciones homepage**

Doy +1 a lo que comenta Rai, creo que ahora se trata de darle vida a esa home tan estática, entiendo que aunque solo aparezcan tres por el momento si el usuario va apoyando/siguiendo los debates/propuestas recomendadas le aparecerán nuevas recomendaciones. 

Al final la idea es que cada vez que el usuario entre a Decide vea contenido nuevo (mucho mejor si está relacionado con sus intereses).

Sobre esto envío un mockup con algunos mini cambios:

- Lo pondría más arriba, justo después del header (que imagino todo el mundo utilizará para el "proceso" más destacado).
- Aprovecharía el ancho total de cada caja, ahora se me queda un poco pequeño.
- No centraría el texto, sí los controles del slider.
- Haría más pequeños los círculos del slider.

Estos cambios puedo verlos con Alessandro o añadirlos yo a vuestra PR, son mini cambios ;)

**Punto 2: Documentos**

En primer lugar creo que habría que añadir ese form al de creación de una propuesta, ahora mismo hay un campo de "Enlace a documentación adicional" y podría quedar muy confuso.

Quizás (cuando este hecho) le daría una vuelta a cambiar un poco los textos, no me convence que bajo la sección de "Documentos" haya también enlaces...

Sobre el lugar del botón si movemos esa parte de documentos al formulario principal se podría dejar en el mismo sitio (no me preocupa para las propuestas ya creadas, y sí para las nuevas).

Otro mockup de esto con un mini cambio, cuando alcanzas el máximo de documentos a subir destacar un poco más el alert ;)

+1 a esa barra de carga, pero por favor, moderna (https://codepen.io/ozzysong/pen/vlIhx) nada old school tipo flash 😂😝

![1_consul_home](https://user-images.githubusercontent.com/15726/28611521-573314b0-71ec-11e7-963e-c892a5484adb.jpg)
<img width="1202" alt="2_documentos" src="https://user-images.githubusercontent.com/15726/28611520-5732917a-71ec-11e7-8dd5-c4651e359c98.png">

**Comment by Senen** [comment]
Adjunto algunos comentarios de Alberto:
> Buenas @sendero, tengo un par de comentarios para el issue del mapa :slightly_smiling_face:

> - Mostraría el mapa directamente para que llame más la atención e invite a poner el marcador (sin tener que hacer otro clic)

> - Si no se puede mostrar directamente cambiaría el `checkbox` por un botón (suelo usar la clase `hollow` para botones dentro de forms y que no destaquen tanto como el botón de “Crear proyecto…“)

> tenemos que darle una vuelta a todos los forms de la página para diferenciar bien los campos obligatorios de los opcionales, como el caso de este mapa, pero no añadiría botón para ocultarlo, es decir si no ponen marcador no sale y ya está, por mi cuantas menos opciones mejor :smile:

**Comment by agileontheweb** [comment]
Después una charlar con Alberto estos es lo que me contesto.

He revisado lo que me has pasado y te cuento:
- +1 a poner los input read-only más oscuros y con el cursor disabled :clap:
- Sobre los campos opcionales:
- El gris de la "nota" es muy claro y se lee regular.
- Me he dado cuenta que poner "(requerido)/(opcional)" en cada campo recarga mucho la interfaz.
- Poner un "*" delante me queda raro.

Revisando mis bookmarks he encontrado esto: https://uxdesign.cc/design-better-forms-96fadca0f49c es un buen artículo para inspirarse

Hay un punto llamado `Ditch the * and denote optional fields` así que esa opción es la que más me gusta, para poner ese `(opcional)` mejor que un `<h4>` como wrapper que no es lo más correcto se puede utilizar un `<p class="help-text">(opcional)</p>`

Para usar esto hay que poner dos cosas, a ese ´<p>´ añadirle “class” e “id”:
<p class="help-text" id="responsible-name-help-text">(opcional)</p>
En el input al que hace referencia añadirle el atributo:
aria: {describedby: "responsible-name-help-text"}` (con el mismo id anterior)

Tienes un ejemplo de esto para fijarte en `app/views/organizations/registrations/new.html.erb` (Líneas 12-15) y está explicado en los docs de Foundation: http://foundation.zurb.com/sites/docs/forms.html#help-text-accessibility-

Para ese texto “(opcional)” se podría crear una key tipo `t("shared.form.optional_field")` así se puede usar sin duplicar :slightly_smiling_face:

Después de todo este rollo, quedaría algo como esta imagen
<img width="900" alt="form_help_text" src="https://user-images.githubusercontent.com/1497150/28661293-7d347ad0-72b6-11e7-98fd-32b479d43784.png">


Otra cosa, cambiar en el texto la palabra click con clic.
