### ISSUE TITLE
A5. Documentable

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#9]
What
======
Allow to attach documents easily to any application model. Configure documentable module for citizen proposals and budget investments.

Original contract definition:
> Propuesta ciudadana y presupuesto participativo (prioritario en este último)
> Un espacio para compartir y colgar documentos ~~o enlaces a documentos relacionados~~ con la propuesta en una pestaña “documentación”.

How
======
* Creating new Document polymorphic model to attach documents to any object.
* Creating Documentable model concern with configurable arguments to easily customize feature restrictions on per model basis.
* Configure new documentable module to proposals and budget investments.
* Add upload document tips to show upload restrictions.(concerns configurable parameters).
* Make uploads through AJAX call
* Use progress bar to show uploads progress to final user.
* Allow to upload multiple documents directly from proposal and budget investments forms as nested resources.
* Allow to add single document to any proposal or budget investment through a single document upload form.

_Te only reason to keep single document upload form is because users cannot edit budget investments projects and therefore they cannot add more documents after creation. With this single document form, authors and administrators can upload documents anytime._

**Upload restrictions (Configurable concern arguments)**
This configurable options allows developers to configure documentable module in different ways to on each documentable model. For example, we want to allow up to 5 documents on proposals but maybe we want to allow only 3 documents on budget investments. Upload restrictions are: 
* max_files_allowed: Allow to define the maximum number of documents on the recipient model.
* max_file_size: Allow to define the maximum size on uploaded files.
* accepted_content_types: Allow to define the accepted content type for file uploads

**Restrictions**
Only proposal or budget investment author or any administrator can upload or destroy documents.
Users can upload up to X MB document size on each documentable object.
Users can upload up to X documents on each documentable object.
Users can upload only allowed documents types (pdf, jpg, png, doc) to each documentable object.

We have configured following restrictions on Proposal and Budget::Investment models.

* max_files_allowed: 3
* max_file_size: 3 MB
* accepted_content_types: [pdf]

**Storage**
Attachment uploader has a dynamic path to decide where to store files: 

* default paperclip path on document creation
* "cached_attachments/user/#{attachment.instance.user_id}" for direct uploads.

When documents are created correctly cached_attachments are deleted and stored in default paperclip path ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename".

**Storage configuration** 
Documents upload is working with local filestorage as well with aws s3 services.

**Filename**
keeping original file name on file uploads.

Screenshots (Updated 27/07/2017)
======

**New Proposal**
Max 3 PDF files .
Max 3 megabyte.

![crear-propuesta](https://user-images.githubusercontent.com/1497150/29724485-f59cf30c-89c8-11e7-8aa0-d068ff44d478.gif)

**Edit Proposal upload single file**
Max 1 PDF files.
Max 3 megabyte.
![show-propuesta-upload-single-file](https://user-images.githubusercontent.com/1497150/29724569-3557c1ac-89c9-11e7-990d-2835dbe057d2.gif)

**Upload button on documentable page (proposal page ot budget investment page)**
![screen shot 2017-07-27 at 17 32 35-fullpage](https://user-images.githubusercontent.com/15726/28679150-957be1fa-72f2-11e7-9468-d66f931f94c3.png)

**User warning: Max number of documents reached**
![screen shot 2017-07-27 at 17 32 17-fullpage](https://user-images.githubusercontent.com/15726/28679151-957fb10e-72f2-11e7-939c-0b46f040f076.png)

**Direct form upload**
![screen shot 2017-07-27 at 17 43 13-fullpage](https://user-images.githubusercontent.com/15726/28679758-8049271e-72f4-11e7-8738-a5c1d589a338.png)

**Direct form upload validations errors**
![screen shot 2017-07-27 at 17 52 05-fullpage](https://user-images.githubusercontent.com/15726/28679756-80451a02-72f4-11e7-8ac5-024737bf9f18.png)

Deploy
=====
Run migrations.

Warnings
=======
None.

Tests
====
Increased model, abilities and feature specs with easily reusable shared examples.

**Comment by Senen** [comment]
Para implementar esta tarea esperaremos a tener la #1 mergeada en master incluyendo el PR de bertoCQ del equipo de consul donde va a crear una tabla Attachment para reutilizar en diferentes modelos.

**Comment by Senen** [comment]
@agileontheweb te adjunto los cambios que nos sugiere Alberto en las pantallas de documentos. Aplica los que son de diseño, de la parte de la barra de carga y del formulario nos ocupamos @taitus  y yo.

**Punto 2: Documentos**

En primer lugar creo que habría que añadir ese form al de creación de una propuesta, ahora mismo hay un campo de "Enlace a documentación adicional" y podría quedar muy confuso.

Quizás (cuando este hecho) le daría una vuelta a cambiar un poco los textos, no me convence que bajo la sección de "Documentos" haya también enlaces... (Los links se van a eliminar)

Sobre el lugar del botón si movemos esa parte de documentos al formulario principal se podría dejar en el mismo sitio (no me preocupa para las propuestas ya creadas, y sí para las nuevas).

Otro mockup de esto con un mini cambio, cuando alcanzas el máximo de documentos a subir destacar un poco más el alert ;) (Hecho)

+1 a esa barra de carga, pero por favor, moderna (https://codepen.io/ozzysong/pen/vlIhx) nada old school tipo flash 😂😝 

<img width="1202" alt="2_documentos" src="https://user-images.githubusercontent.com/15726/28611520-5732917a-71ec-11e7-8dd5-c4651e359c98.png">

**Comment by agileontheweb** [comment]
A la espera de respuesta de Alberto

campo opcional 1:
Solo el texto ‘opcional’ al  lado de la etiqueta
Esta requiere un H4 como wrapper como no podemos meter un tag en un label.

campo opcional 2:
Texto ‘opcional’ o ‘requerido’ al  lado de la etiqueta
Esta requiere un H4 como wrapper como no podemos meter un tag en un label.

campo opcional 3
Señalar al comienzo de cada form con un texto destacado los campo requerido y añadir un * en cada label que lo requiere.

campo opcional 4
Señalar al comienzo de cada form con un texto normal y añadir un * en cada label que lo requiere.

Input del mapa de color un poco más gris de momento que son read-only y el cursor con el icono del disabled.

![campos-opcional-1](https://user-images.githubusercontent.com/1497150/28625368-4ce07d2e-721c-11e7-833b-f70a44d0afd6.jpg)

![campos-opcional-2](https://user-images.githubusercontent.com/1497150/28625369-4d01a2d8-721c-11e7-94ad-13d67b9d0dfe.jpg)

![campos-opcional-3](https://user-images.githubusercontent.com/1497150/28625370-4d02271c-721c-11e7-99de-884037281ef3.jpg)

![campos-opcional-4](https://user-images.githubusercontent.com/1497150/28625371-4d06508a-721c-11e7-9131-9a266e987837.jpg)

**Comment by Senen** [comment]
First screenshots versións with links:

**Upload PDF**
![captura de pantalla 2017-07-24 a las 14 47 25](https://user-images.githubusercontent.com/15726/28524055-52aa224e-707f-11e7-9225-9ee32c5dc4ed.png)

**Add Link**
![captura de pantalla 2017-07-24 a las 14 51 53](https://user-images.githubusercontent.com/15726/28524169-a8e90fda-707f-11e7-89bc-c1eabace96f8.png)

**Validation errors**
![captura de pantalla 2017-07-24 a las 14 48 12](https://user-images.githubusercontent.com/15726/28524078-5f29a9d6-707f-11e7-9639-915fbdda1d54.png)
![captura de pantalla 2017-07-24 a las 14 48 00](https://user-images.githubusercontent.com/15726/28524077-5f214728-707f-11e7-8224-8307bc1ce5a8.png)

**Document tab and documents list. Maximum number of documents allowed notice**
![max-download](https://user-images.githubusercontent.com/1497150/28474802-3943f87a-6e4a-11e7-9625-2b1baa6a1418.jpg)

**Comment by agileontheweb** [comment]
Screenshots GIF (Updated 25/08/2017)

**New Proposal**
Max 3 PDF files .
Max 3 megabyte.

![crear-propuesta](https://user-images.githubusercontent.com/1497150/29724485-f59cf30c-89c8-11e7-8aa0-d068ff44d478.gif)

**Edit Proposal upload single file**
Max 1 PDF files.
Max 3 megabyte.
![show-propuesta-upload-single-file](https://user-images.githubusercontent.com/1497150/29724569-3557c1ac-89c9-11e7-990d-2835dbe057d2.gif)

**Comment by Senen** [comment]
Merged https://github.com/consul/consul/pull/1809. 😄 🎉
